spring:
  datasource:
    url: ${secrets.DB_URL}
    username: ${secrets.DB_USERNAME}
    password: ${secrets.DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${secrets.GOOGLE_CLIENT_ID}
            client-secret: ${secrets.GOOGLE_CLIENT_SECRET}

springdoc:
  override-with-generic-response: true

logging:
  file:
    name: logs/app-prod.log
  level:
    root: warn
    io.github.renatoconrado: warn
    org.springframework:
      web: warn
      security: error
