spring:
  application:
    name: Library Api - ${spring.profiles.active}
  profiles: # dev | prod
    active: prod
  config:
    import: optional:secrets/application-secrets.yml

logging:
  pattern:
    console: '%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n'

springdoc:
  override-with-generic-response: false

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: "*"
