spring:
  application.name: Library Api
  config.import: optional:application-secrets.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    properties.hibernate.format_sql: true
  security.oauth2.client.registration:
    google:
      client-id: ${secrets.GOOGLE_CLIENT_ID}
      client-secret: ${secrets.GOOGLE_CLIENT_SECRET}
logging:
  include-application-group: false
  include-application-name: false
  pattern:
    dateformat: h:m:s