spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${secrets.GOOGLE_CLIENT_ID}
            client-secret: ${secrets.GOOGLE_CLIENT_SECRET}

logging:
  file:
    name: logs/app-dev.log
  level:
    root: info
    io.github.renatoconrado: debug
    org.springframework:
      web: info
      security: debug
  pattern:
    console: '%clr(%d{h:m:s}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n'