@url = {{urls.books}}
@id = 66982b46-5f47-45dc-9458-c08291772452
### POST
POST {{url}}
Content-Type: application/json

{
  "isbn": "978-0-14-044913-6",
  "title": "Travels",
  "releaseDate": "2020-01-01",
  "genres": "FICTION",
  "price": 50,
  "idAuthor": "7d1ebe9e-b5b1-4c5b-9127-a82da1e29c0f"
}

### Get All
GET {{url}}

> {%
    if (!response.body.length) {
        client.exit();
    }
    /**@type {string} */
    const lastId = response.body[response.body.length - 1].id;
    client.global.set("id", lastId || "");
    client.log(`Element: ${JSON.stringify(lastId)}`);
%}

### Query isbn
@isbn = 978-0-306-40615-7
GET {{url}}?isbn={{isbn}}

### Query title
@title = travel
GET {{url}}?title={{title}}

### Query genre
@genres = FICTION
GET {{url}}?genres={{genres}}

### Query release Year
@releaseYear = 2020
GET {{url}}?releaseYear={{releaseYear}}

### Query author Name
@author = macarena
GET {{url}}?author={{author}}

### Get By Id
GET {{url}}/{{id}}

### UPDATE
PUT {{url}}/{{id}}
Content-Type: application/json

{
  "isbn": "",
  "title": "",
  "releaseDate": "",
  "genres": "",
  "author": ""
}

### DELETE
DELETE {{url}}/{{id}}