@url = {{urls.authors}}
### Create Author
POST {{url}}
Content-Type: application/json
Authorization: Basic admin 123

{
  "name": "Jhon lock",
  "birthdate": "1989-02-16",
  "citizenship": "America"
}

### Get All
@name =
@citizenship =
GET {{url}}?name={{name}}&citizenship={{citizenship}}

> {%
    const body = response.body;
    if (!body.length) {
        client.exit();
    }
    const lastId = body[body.length - 1].id;
    client.global.set("id", lastId || "");
    client.log(`Element: ${JSON.stringify(lastId)}`);
%}

### Get By Id
GET {{url}}/{{id}}

### UPDATE
PUT {{url}}/{{id}}
Content-Type: application/json

{
  "name": "macarena",
  "birthdate": "1989-02-16",
  "citizenship": "America"
}

### DELETE
DELETE {{url}}/{{id}}
